version: '2'

services:
  mysql:
    image: mysql
    container_name: yourls-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootsecretpassword
      MYSQL_USER: yourls
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: yourls
    volumes:
      - ./volumes/var/lib/mysql:/var/lib/mysql:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "7"
    privileged: true

  yourls:
    # replace "image" with "build" for developing purpose
    # build: ./
    image: guessi/docker-yourls
    container_name: yourls
    links:
      - mysql:mysql
    environment:
      YOURLS_DB_USER: yourls
      YOURLS_DB_PASS: mysecretpassword
      YOURLS_DB_NAME: yourls
      YOURLS_DB_HOST: mysql
      YOURLS_SITE: http://localhost
      YOURLS_COOKIEKEY: 63d8cd986cded909158fcc00
      YOURLS_ADMIN_USERNAME: admin
      YOURLS_ADMIN_PASSWORD: my@dminP@ss
    ports:
      - 80:80
    depends_on:
      - mysql
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "7"
